analytics:
  google: UA-71263000-1
color:
  brandColors:
    - '#000000'
    - '#fe0000'
    - '#ffff00'
    - '#889101'
    - '#0038e9'
  brandStrength: 0.6875
  lightness: 0.75
  rhythmicContrast: 0.226257
  saturation: 0.375
cta: {}
layout_spectrum: 0.92356
name: FullStack
opengraph: {}
purpose: []
typography_spectrum: 0.82415
