name: FullStack
favicon: null
layout_spectrum: 0.92356
typography_spectrum: 0.82415
title: Convergence in IT Automation and Orchestration
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71263000-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#200e0d'
    - '#bc2920'
    - '#ff7c39'
    - '#7f5e25'
    - '#ffd651'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0.226257
purpose: []
