name: FullStack
favicon: null
layout_spectrum: 0.92356
typography_spectrum: 0.82415
title: Discovering the next convergence in Information Technology and Information Security Automation
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71263000-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fe0000'
    - '#ffff00'
    - '#889101'
    - '#0038e9'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
